spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/${DB_NAME:test_db}
    username: ${DB_USER:pguser}
    password: ${DB_PASSWORD:uitc}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: uitc
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate   # 开发时使用 update 会自动建表；生产环境用 validate 或 none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: ${DB_HOST:127.0.0.1}
      password: ${DB_PASSWORD:uitc}
      port: 6379
      database: 0
      timeout: 5000

langchain4j:
  open-ai:
    chat-model:
        base-url: ${LLM_BASE_URL:https://ark.cn-beijing.volces.com/api/coding/v3}
        api-key: ${LLM_API_KEY:change-me}
        model-name: ${LLM_MODEL:GLM-5.2}
mybatis:
  type-handlers-package: com.uit.api.handler